#!/bin/bash

. ~/.bash_profile

cd ~/current

echo "===================================" >> log/cron_every_five_minutes 2>&1
if [ -f ~/primary ]; then
  echo "Getting Tweets"                    >> log/cron_every_five_minutes 2>&1
  ./script/runner 'Cron.get_tweets'        >> log/cron_every_five_minutes 2>&1
fi

